language: java
#jdk:
#- openjdk8

matrix:
  include:
    - dist: trusty
      jdk: openjdk8
    - dist: trusty
      jdk: openjdk11
    - dist: trusty
      jdk: openjdk14

sudo: required
#dist: trusty
services:
- docker

script: "./gradlew clean licenseMain build --no-daemon $jdk"

before_deploy:
- echo build start... gadtry
before_cache:
- rm -f  $HOME/.gradle/caches/modules-2/modules-2.lock
- rm -fr $HOME/.gradle/caches/*/plugin-resolution/

after_success:
  - bash <(curl -s https://codecov.io/bash)

cache:
  directories:
  - "$HOME/.gradle/caches/"
  - "$HOME/.gradle/wrapper/"
